import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "ProjectXplore",
  description: "Generated by Parambrata Ghosh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster/>
        </body>
    </html>
  );
}
