import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useUser from "@/hooks/useUser";
import STATES from "@/lib/utils/constants";
import { redirect } from "next/navigation";
import MainLayoutPage from "./mainLayoutPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayoutPage>
          {children}

        </MainLayoutPage>
      </body>
    </html>
  );
}
